### PR TITLE
Wrap enumerators to avoid JobIteration deprecation

### LINKED ISSUE #1132: Weekly CI run failed
https://github.com/Shopify/maintenance_tasks/actions/runs/12343293917

### PR DESCRIPTION
**Pull request by etiennebarrie**
Fix #1132 

The new version of job-iteration makes CI fail because it adds a deprecation. This resolves the deprecation by always wrapping enumerators with `JobIteration.enumerator_builder.wrap`.

### CODE REVIEW

File: app/jobs/concerns/maintenance_tasks/task_job_concern.rb [hunk 1]
```diff
@@ -75,6 +76,9 @@ def build_enumerator(_run, cursor:)
         MSG
       end
 
+      unless @collection_enum.is_a?(JobIteration.enumerator_builder::Wrapper)
```
Comment (nvasilevski) [inline app/jobs/concerns/maintenance_tasks/task_job_concern.rb:79]: Is there a risk of `Wrapper` constant not existing in `JobIteration.enumerator_builder` namespace?
